##################################################
# PROGRAMS - conf/programs.conf
# Khai báo biến app để dùng trong keybinding
##################################################

$terminal   = kitty
$terminal2  = foot
$filemanager= thunar
$browser    = firefox
$editor     = kitty -e nvim
$launcher   = rofi -show drun -theme ~/.config/rofi/launcher.rasi
$runner     = rofi -show run  -theme ~/.config/rofi/runner.rasi
$emoji      = rofi -show emoji -theme ~/.config/rofi/emoji.rasi
$clipboard = cliphist list | rofi -dmenu -theme ~/.config/rofi/clipboard.rasi | cliphist decode | wl-copy
$wallpaper  = ~/.config/scripts/wallpaper.sh pick
$screenshot = ~/.config/scripts/screenshot.sh
$colorpick  = hyprpicker -a
$calc       = rofi -show calc -modi calc -no-show-match -no-sort -theme ~/.config/rofi/calc.rasi
$wlogout    = wlogout --protocol layer-shell -b 5 -T 400 -B 400
$swaync     = swaync-client -t
