##################################################
# WORKSPACES - conf/workspaces.conf
##################################################

workspace = 1,  monitor:desc:, default:true, persistent:true
workspace = 2,  monitor:desc:, persistent:true
workspace = 3,  monitor:desc:, persistent:true
workspace = 4,  monitor:desc:, persistent:true
workspace = 5,  monitor:desc:, persistent:true
workspace = 6,  monitor:desc:, persistent:true
workspace = 7,  monitor:desc:, persistent:true
workspace = 8,  monitor:desc:, persistent:true
workspace = 9,  monitor:desc:, persistent:true
workspace = 10, monitor:desc:, persistent:true

# Special workspace (scratchpad)
workspace = special:scratch, on-created-empty:kitty --class=scratch
workspace = special:music,   on-created-empty:spotify
